all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: true
      ignition_container_name: ignition_gibraltar
      ignition_volume_name: gibraltar_ignition_data_gibraltar
      ignition_release_path: /opt/ignition-release
      ignition_backup_path: /opt/ignition-backups
